plugins:
  - rubocop-rails
  - rubocop-performance

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'db/*_schema.rb'
    - 'bin/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
    - 'config/environments/**/*'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Layout/LineLength:
  Max: 120

Style/HashSyntax:
  EnforcedStyle: ruby19

Rails/SafeNavigation:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Metrics/BlockLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Style/SymbolArray:
  Enabled: true
  EnforcedStyle: percent

Style/StringLiterals:
  EnforcedStyle: single_quotes